version: '3.8'

services:
  app:
    image: htayhtaythwe717/book-flights:0.2
    container_name: flight_laravel
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flight_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flight_booking_system
      MYSQL_USER: htaythwe
      MYSQL_PASSWORD: htayhtaythwe2001
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

