services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: mysql
      - key: DB_DATABASE
        value: flight_booking_system
      - key: DB_USERNAME
        value: htaythwe
      - key: DB_PASSWORD
        value: htaythwe

  - type: web
    name: nginx-proxy
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./nginx/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars: []
    ports:
      - port: 80

  - type: pserv
    name: mysql
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ""
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: flight_booking_system
      - key: MYSQL_USER
        value: htaythwe
      - key: MYSQL_PASSWORD
        value: htaythwe
    disk:
      name: mysql_data
      mountPath: /var/lib/mysql
      sizeGB: 1
