services:
  - name: laravel
    type: docker
    image: htayhtaythwe717/book-flights:laravel_0.1
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: mysql
      - key: DB_DATABASE
        value: flight_booking_system
      - key: DB_USERNAME
        value: htaythwe
      - key: DB_PASSWORD
        value: htaythwe
    restartPolicy: always

  - name: nginx
    type: docker
    dockerfilePath: ./nginx/Dockerfile
    envVars: []
    ports:
      - port: 80
        protocol: http
    restartPolicy: always
    dependsOn:
      - laravel

databases:
  - name: mysql
    plan: standard
    userName: htaythwe
    userPassword: htaythwe
    databaseName: flight_booking_system
    region: oregon
