version: 0.1
services:
  laravel:
    image: htayhtaythwe717/book-flights:laravel_0.1
    env:
      APP_ENV: production
      DB_HOST: mysql
      DB_DATABASE: flight_booking_system
      DB_USERNAME: htaythwe
      DB_PASSWORD: htaythwe
    expose:
      - 9000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - laravel
    ports:
      - port: 80

  mysql:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flight_booking_system
      MYSQL_USER: htaythwe
      MYSQL_PASSWORD: htaythwe
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - port: 3306

volumes:
  mysql_data:
