apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: htayhtaythwe717/book-flights:react_0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
    - port: 80
      targetPort: 80
